"""
Initialize data directory structure for the challenge dataset.
"""
from pathlib import Path
import json


def create_directory_structure():
    """Create the expected data directory structure."""
    
    # Create main data directory
    data_dir = Path("data")
    data_dir.mkdir(exist_ok=True)
    
    # Create clips directory
    clips_dir = data_dir / "clips"
    clips_dir.mkdir(exist_ok=True)
    
    # Create store directories (5 stores as per challenge)
    stores = [
        "STORE_BLR_002",
        "STORE_DEL_001",
        "STORE_MUM_003",
        "STORE_BLR_004",
        "STORE_PUN_001"
    ]
    
    for store_id in stores:
        store_dir = clips_dir / store_id
        store_dir.mkdir(exist_ok=True)
        
        # Create placeholder files
        cameras = ["entry_camera.mp4", "floor_camera.mp4", "billing_camera.mp4"]
        for camera in cameras:
            placeholder = store_dir / f"{camera}.placeholder"
            placeholder.write_text(f"Place {camera} for {store_id} here")
    
    # Create sample store_layout.json template
    store_layout_template = {
        "stores": [
            {
                "store_id": "STORE_BLR_002",
                "name": "Bangalore Store 2",
                "zones": [
                    {
                        "zone_id": "SKINCARE",
                        "name": "Skincare Section",
                        "bbox": [0.1, 0.2, 0.4, 0.6],
                        "camera_coverage": ["CAM_FLOOR_01"]
                    },
                    {
                        "zone_id": "HAIRCARE",
                        "name": "Haircare Section",
                        "bbox": [0.4, 0.2, 0.7, 0.6],
                        "camera_coverage": ["CAM_FLOOR_01"]
                    },
                    {
                        "zone_id": "MAKEUP",
                        "name": "Makeup Section",
                        "bbox": [0.1, 0.6, 0.4, 0.9],
                        "camera_coverage": ["CAM_FLOOR_01"]
                    },
                    {
                        "zone_id": "BILLING",
                        "name": "Billing Counter",
                        "bbox": [0.7, 0.1, 0.9, 0.3],
                        "camera_coverage": ["CAM_BILLING_01"]
                    }
                ],
                "open_hours": {
                    "start": "10:00",
                    "end": "22:00"
                }
            }
        ]
    }
    
    layout_file = data_dir / "store_layout.json.template"
    with open(layout_file, 'w') as f:
        json.dump(store_layout_template, f, indent=2)
    
    # Create sample POS transactions template
    pos_template = """store_id,transaction_id,timestamp,basket_value_inr
STORE_BLR_002,TXN_00441,2026-03-03T14:38:12Z,1240.00
STORE_BLR_002,TXN_00442,2026-03-03T14:41:55Z,680.00
STORE_DEL_001,TXN_00443,2026-03-03T14:45:30Z,890.00
"""
    
    pos_file = data_dir / "pos_transactions.csv.template"
    pos_file.write_text(pos_template)
    
    # Create README in data directory
    readme_content = """# Data Directory

This directory should contain the challenge dataset:

## Required Files

1. **CCTV Clips** (`clips/`)
   - 5 stores, 3 cameras each
   - 20 minutes per clip
   - Format: MP4, 1080p @ 15fps
   
   Structure:
   ```
   clips/
   ├── STORE_BLR_002/
   │   ├── entry_camera.mp4
   │   ├── floor_camera.mp4
   │   └── billing_camera.mp4
   ├── STORE_DEL_001/
   │   └── ...
   └── ...
   ```

2. **Store Layout** (`store_layout.json`)
   - Zone definitions for each store
   - Camera coverage mapping
   - Open hours
   
   See `store_layout.json.template` for format.

3. **POS Transactions** (`pos_transactions.csv`)
   - Timestamped transaction records
   - Format: store_id, transaction_id, timestamp, basket_value_inr
   
   See `pos_transactions.csv.template` for format.

4. **Sample Events** (`sample_events.jsonl`)
   - 200 example events in expected schema
   - Used for validation

5. **Assertions** (`assertions.py`)
   - 10 test assertions for scoring
   - Provided by challenge organizers

## Output Files

- `events.jsonl` - Generated by detection pipeline
- `output/` - Additional pipeline outputs

## Notes

- Templates are provided for reference
- Rename `.template` files to actual filenames after adding real data
- Do not commit large video files to git (see .gitignore)
"""
    
    readme_file = data_dir / "README.md"
    readme_file.write_text(readme_content, encoding='utf-8')
    
    print("✓ Data directory structure created")
    print(f"\nCreated:")
    print(f"  - {data_dir}/")
    print(f"  - {clips_dir}/")
    for store in stores:
        print(f"    - {clips_dir / store}/")
    print(f"  - {layout_file}")
    print(f"  - {pos_file}")
    print(f"  - {readme_file}")
    
    print(f"\nNext steps:")
    print(f"  1. Place CCTV clips in data/clips/<store_id>/")
    print(f"  2. Add store_layout.json (use template as reference)")
    print(f"  3. Add pos_transactions.csv (use template as reference)")
    print(f"  4. Add sample_events.jsonl from challenge")
    print(f"  5. Add assertions.py from challenge")


if __name__ == "__main__":
    create_directory_structure()
